### ISSUE TITLE
What am I supposed to set for SourceID in DataSift Writer config?

### ISSUE THREAD

**Issue by andrewtabit** [datasift/datasift-connector#19]
I have been using DataSift to pull historical data from Twitter and have to move to GNIP now. For that, I just launched AWS instance with DataSift Connector (using your instruction) and I want to connect it to my DataSift account. There's `SourceID` parameter that I need to provide. It is used in POST url:
```
POST https://in.datasift.com:443/<SourceID>
```
It should definitely be something like `twitter`:
```
POST https://in.datasift.com:443/twitter/
```
but for me it is not working. It keeps saying `{"error":"Unknown user source"}`. Any insights on that?

NOTE: Twitter is activated in my account (https://www.evernote.com/l/ACcmvZQu8xFEtJ-U25nPg1v8sDjk_jy2cjw).

**Comment by igorb** [comment]
is it the right article http://dev.datasift.com/docs/sources/public-sources/twitter/twitter-source ?

**Comment by 3ft9** [comment]
You need to create a Twitter/Gnip managed source. Please contact your account manager for details.
