### ISSUE TITLE
Problems with packer instructions in README.md

### ISSUE THREAD

**Issue by nwolff** [datasift/datasift-connector#39]
For version https://github.com/datasift/datasift-connector/releases/tag/1.0.15-1

I wanted to deploy the datasift-connector to EC2 and followed these instructions https://github.com/datasift/datasift-connector#quick-start---deployment-to-ec2 . I ran into a number of problems:

- The quickstart fails to mention that https://downloads.chef.io/chef-dk/ must be installed (it's mentioned only later in the page)
- When packer tried to create the l2.tiny instance to load the first ami I was getting "'A subnet ID or network interface ID is required to carry out the request." errors. I had to edit the `datasift-connector/packer/ami.json` file to set the instance type to `m3.medium` which can run in EC2 classic.
- Once the ami was provisioned and packer started running I had to accept the license agreement https://aws.amazon.com/marketplace/ordering?productId=74e73035-3435-48d6-88e0-89cc02ad83ee&ref_=dtl_psb_continue&region=us-east-1 . There is no mention of that in the docs, and also I don't really know what the financial impact is? Am I paying extra for the ami used by packer during the build? For the ami that packer ends up building and that I will be running for a long time?
- The image gets built in the us-east region. I had to manually copy it to the eu-region where my servers are running (and it took about 30 minutes).

Would it be possible for you to just publish the ami with the datasift-connector to EC2?

**Comment by AndyJS** [comment]
Linked PR #54 should cover off the issues listed with documentation.

A published AMI is something we would like to provide. Any further details will be provided as comments against new issue #55.
