### ISSUE TITLE
Support Gnip historics

### ISSUE THREAD

**Issue by jamesbloomer** [datasift/datasift-connector#5]

**Comment by igorb** [comment]
Guys, are you going to support "Historic Reader" in gnip?
thanks.

**Comment by jamesbloomer** [comment]
The plan is to support HistoricalPowerTrack.

**Comment by AndyJS** [comment]
Initial implementation for Historical PowerTrack support was merged in PR #36 & released as part of 1.0.19-1: https://github.com/datasift/datasift-connector/releases/tag/1.0.19-1

Further improvements will be made to improve ease of use, metrics & additional logging.
